In [4]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras

print(tf.__version__)
print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__, module.__version__)

2.2.0
sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
matplotlib 3.2.1
numpy 1.18.5
pandas 1.0.4
sklearn 0.23.1
tensorflow 2.2.0
tensorflow.keras 2.3.0-tf


In [5]:
# tfrecord 文件格式---往下层层分类
# -> tf.train.Example
#    -> tf.train.Features -> {"key": tf.train.Feature}
#       -> tf.train.Feature -> tf.train.ByteList/FloatList/Int64List

#学习时，从低往上练习
favorite_books = [name.encode('utf-8')
                  for name in ["machine learning", "cc150"]]
print(favorite_books)
favorite_books_bytelist = tf.train.BytesList(value = favorite_books)
print(type(favorite_books_bytelist))
print(favorite_books_bytelist)

#hours设置到0-24之间
hours_floatlist = tf.train.FloatList(value = [15.5, 9.5, 7.0, 8.0])
print(type(hours_floatlist))
print(hours_floatlist)

age_int64list = tf.train.Int64List(value = [42])
print(type(age_int64list))
print(age_int64list)
#进一步，开搞features
features = tf.train.Features(
    feature = {
        "favorite_books": tf.train.Feature(
            bytes_list = favorite_books_bytelist),
        "hours": tf.train.Feature(
            float_list = hours_floatlist),
        "age": tf.train.Feature(int64_list = age_int64list),
    }
)
print(type(features))
print(features) #类似于json的格式

[b'machine learning', b'cc150']
<class 'tensorflow.core.example.feature_pb2.BytesList'>
value: "machine learning"
value: "cc150"

<class 'tensorflow.core.example.feature_pb2.FloatList'>
value: 15.5
value: 9.5
value: 7.0
value: 8.0

<class 'tensorflow.core.example.feature_pb2.Int64List'>
value: 42

<class 'tensorflow.core.example.feature_pb2.Features'>
feature {
  key: "age"
  value {
    int64_list {
      value: 42
    }
  }
}
feature {
  key: "favorite_books"
  value {
    bytes_list {
      value: "machine learning"
      value: "cc150"
    }
  }
}
feature {
  key: "hours"
  value {
    float_list {
      value: 15.5
      value: 9.5
      value: 7.0
      value: 8.0
    }
  }
}



In [6]:
#example又在外面加了features封装
example = tf.train.Example(features=features)
print(type(example))
print(example)
#需要把Example对象进行序列化后，才能写入文件
serialized_example = example.SerializeToString()
print(type(serialized_example))
print(serialized_example)
print(len(serialized_example))

<class 'tensorflow.core.example.example_pb2.Example'>
features {
  feature {
    key: "age"
    value {
      int64_list {
        value: 42
      }
    }
  }
  feature {
    key: "favorite_books"
    value {
      bytes_list {
        value: "machine learning"
        value: "cc150"
      }
    }
  }
  feature {
    key: "hours"
    value {
      float_list {
        value: 15.5
        value: 9.5
        value: 7.0
        value: 8.0
      }
    }
  }
}

<class 'bytes'>
b'\n\\\n\x1d\n\x05hours\x12\x14\x12\x12\n\x10\x00\x00xA\x00\x00\x18A\x00\x00\xe0@\x00\x00\x00A\n-\n\x0efavorite_books\x12\x1b\n\x19\n\x10machine learning\n\x05cc150\n\x0c\n\x03age\x12\x05\x1a\x03\n\x01*'
94


In [7]:
!ls

generate_csv		   tf02_data_generate_csv.ipynb
generate_tfrecords	   tf03-tfrecord_basic_api.ipynb
generate_tfrecords_zip	   tf04_data_generate_tfrecord.ipynb
tf01-data_basic_api.ipynb


In [8]:
!rm -rf tfrecord_basic

In [9]:
#生成test.tfrecords文件
output_dir = 'tfrecord_basic'
if not os.path.exists(output_dir):
    os.mkdir(output_dir)
filename = "test.tfrecords"
filename_fullpath = os.path.join(output_dir, filename)
with tf.io.TFRecordWriter(filename_fullpath) as writer:
    #把serialized_example写3遍到test.tfrecords里边
    for i in range(3):
        writer.write(serialized_example)


In [10]:
!ls -l tfrecord_basic

总用量 4
-rw-rw-r-- 1 luke luke 330 Jul 24 10:22 test.tfrecords


In [11]:
#读取record并打印
dataset = tf.data.TFRecordDataset([filename_fullpath])
for serialized_example_tensor in dataset:
    print(serialized_example_tensor)

tf.Tensor(b'\n\\\n\x1d\n\x05hours\x12\x14\x12\x12\n\x10\x00\x00xA\x00\x00\x18A\x00\x00\xe0@\x00\x00\x00A\n-\n\x0efavorite_books\x12\x1b\n\x19\n\x10machine learning\n\x05cc150\n\x0c\n\x03age\x12\x05\x1a\x03\n\x01*', shape=(), dtype=string)
tf.Tensor(b'\n\\\n\x1d\n\x05hours\x12\x14\x12\x12\n\x10\x00\x00xA\x00\x00\x18A\x00\x00\xe0@\x00\x00\x00A\n-\n\x0efavorite_books\x12\x1b\n\x19\n\x10machine learning\n\x05cc150\n\x0c\n\x03age\x12\x05\x1a\x03\n\x01*', shape=(), dtype=string)
tf.Tensor(b'\n\\\n\x1d\n\x05hours\x12\x14\x12\x12\n\x10\x00\x00xA\x00\x00\x18A\x00\x00\xe0@\x00\x00\x00A\n-\n\x0efavorite_books\x12\x1b\n\x19\n\x10machine learning\n\x05cc150\n\x0c\n\x03age\x12\x05\x1a\x03\n\x01*', shape=(), dtype=string)


In [20]:
# VarLenFeature是变长的，得到的是sparseTensor,要通过to_dense变为Tensor，
# 如果FixedLenFeature，得到的是Tensor，必须传入原来保存时数据的shape
expected_features = {
    "favorite_books": tf.io.FixedLenFeature([2],dtype = tf.string),
#     "hours": tf.io.FixedLenFeature([4],dtype = tf.float32),
    "hours": tf.io.VarLenFeature(dtype = tf.float32),
    "age": tf.io.FixedLenFeature([], dtype = tf.int64),
}
dataset = tf.data.TFRecordDataset([filename_fullpath])
#sparse tensor 存储稀疏矩阵的时候效率比较高
for serialized_example_tensor in dataset:
    example = tf.io.parse_single_example(
        serialized_example_tensor,#游标
        expected_features #解析的类型
    )
    print(example)
    #把books从sparse tensor解析出来
#     books = tf.sparse.to_dense(example["favorite_books"],
#                                default_value=b"")
#     print(books)
#     #这里是为了把两个字符串解析出来
#     for book in books:
#         print(book.numpy().decode("UTF-8"))
    for i in example["favorite_books"]:
        print(i.numpy().decode("UTF-8"))
    print('-'*50)
    hours = tf.sparse.to_dense(example["hours"])
    print(hours)
    for hour in hours:
        print(hour.numpy())
    print('-'*50)
    print(example["age"].numpy())
    

{'hours': <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x7f019460cf28>, 'age': <tf.Tensor: shape=(), dtype=int64, numpy=42>, 'favorite_books': <tf.Tensor: shape=(2,), dtype=string, numpy=array([b'machine learning', b'cc150'], dtype=object)>}
machine learning
cc150
--------------------------------------------------
tf.Tensor([15.5  9.5  7.   8. ], shape=(4,), dtype=float32)
15.5
9.5
7.0
8.0
--------------------------------------------------
42
{'hours': <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x7f019456e860>, 'age': <tf.Tensor: shape=(), dtype=int64, numpy=42>, 'favorite_books': <tf.Tensor: shape=(2,), dtype=string, numpy=array([b'machine learning', b'cc150'], dtype=object)>}
machine learning
cc150
--------------------------------------------------
tf.Tensor([15.5  9.5  7.   8. ], shape=(4,), dtype=float32)
15.5
9.5
7.0
8.0
--------------------------------------------------
42
{'hours': <tensorflow.python.framework.sparse_tensor.SparseTenso

In [21]:
#把tfrecord存为压缩文件
filename_fullpath_zip = filename_fullpath + '.zip'
options = tf.io.TFRecordOptions(compression_type = "GZIP")
with tf.io.TFRecordWriter(filename_fullpath_zip, options) as writer:
    for i in range(3):
        writer.write(serialized_example)

In [22]:
!ls -l tfrecord_basic

总用量 8
-rw-rw-r-- 1 luke luke 330 Jul 24 10:22 test.tfrecords
-rw-rw-r-- 1 luke luke 127 Jul 24 11:14 test.tfrecords.zip


In [25]:
#压缩后的文件的读取方法
dataset_zip = tf.data.TFRecordDataset([filename_fullpath_zip], 
                                      compression_type= "GZIP")
for serialized_example_tensor in dataset_zip:
    example = tf.io.parse_single_example(
        serialized_example_tensor,
        expected_features)
    print(example)

{'hours': <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x7f01ed438b38>, 'age': <tf.Tensor: shape=(), dtype=int64, numpy=42>, 'favorite_books': <tf.Tensor: shape=(2,), dtype=string, numpy=array([b'machine learning', b'cc150'], dtype=object)>}
{'hours': <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x7f01ed438c18>, 'age': <tf.Tensor: shape=(), dtype=int64, numpy=42>, 'favorite_books': <tf.Tensor: shape=(2,), dtype=string, numpy=array([b'machine learning', b'cc150'], dtype=object)>}
{'hours': <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x7f01ed438b38>, 'age': <tf.Tensor: shape=(), dtype=int64, numpy=42>, 'favorite_books': <tf.Tensor: shape=(2,), dtype=string, numpy=array([b'machine learning', b'cc150'], dtype=object)>}
